Repository knative-sandbox/container-freezer, pull requests merged in 2021-12, with the labels that each got.

#46 Use string formatting functions for logging
  pkg/daemon/handler.go
Labels: cla: yes, lgtm, approved, size/XS

#47 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#48 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#35 Freeze/thaw all non-QP containers
  cmd/daemon/main.go
  cmd/daemon/main_test.go
  pkg/daemon/handler.go
  pkg/daemon/handler_test.go
  pkg/freeze/containerd/pause.go
  pkg/freeze/containerd/pause_test.go
Labels: cla: yes, size/L, lgtm, approved

#50 Tidy freeze functions a bit
  cmd/daemon/main.go
  pkg/freeze/containerd/pause.go
  pkg/freeze/containerd/pause_test.go
Labels: size/L, lgtm, approved

#51 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#53 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#54 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#56 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#55 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, size/XS
