Repository knative-sandbox/container-freezer, pull requests merged in 2021-11, with the labels that each got.

#27 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#28 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#29 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, size/S, approved

#30 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, lgtm, approved, size/XS

#31 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#36 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, lgtm, approved, size/M

#38 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/S, approved

#39 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS

#34 Fix formatting issue with status/wg readme box
  README.md
Labels: cla: yes, lgtm, approved, size/XS

#32 Simplifies message body handling
  pkg/daemon/handler.go
Labels: cla: yes, lgtm, approved, size/XS

#40 log pod names on pause/resume requests
  pkg/daemon/handler.go
  pkg/daemon/handler_test.go
Labels: cla: yes, lgtm, size/S, approved

#41 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/S, approved

#42 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, lgtm, approved, size/XS
