Repository knative-sandbox/container-freezer, pull requests merged in 2022-05, with the labels that each got.

#111 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#112 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#114 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#115 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#116 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#117 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#120 Update working group sponsor
  OWNERS
  README.md
Labels: lgtm, approved, size/XS

#121 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved
