Repository knative-sandbox/container-freezer, pull requests merged in 2022-01, with the labels that each got.

#57 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#59 Set logging config/level and runtimeType via env variables
  cmd/daemon/main.go
  config/300-daemon-containerd.yaml
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/.travis.yml
  vendor/github.com/kelseyhightower/envconfig/LICENSE
  vendor/github.com/kelseyhightower/envconfig/MAINTAINERS
  vendor/github.com/kelseyhightower/envconfig/README.md
  vendor/github.com/kelseyhightower/envconfig/doc.go
  vendor/github.com/kelseyhightower/envconfig/env_os.go
  vendor/github.com/kelseyhightower/envconfig/env_syscall.go
  vendor/github.com/kelseyhightower/envconfig/envconfig.go
  vendor/github.com/kelseyhightower/envconfig/go.mod
  vendor/github.com/kelseyhightower/envconfig/usage.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL, ok-to-test

#61 set env variables via configmap
  config/300-daemon-containerd.yaml
  config/400-configmap.yaml
Labels: lgtm, size/S, approved, needs-ok-to-test

#63 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#64 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#66 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS

#67 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/CHANGELOG.md
  vendor/github.com/go-logr/logr/CONTRIBUTING.md
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#69 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/S, approved

#70 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#71 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#73 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: lgtm, approved, size/XS

#72 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#74 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M
