Repository knative-sandbox/container-freezer, pull requests merged in 2022-03, with the labels that each got.

#85 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: lgtm, approved, size/XS

#87 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#88 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#89 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#91 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS

#93 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: lgtm, approved, size/XS

#96 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#95 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/XL

#97 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/modules.txt
Labels: lgtm, size/S, approved
