Repository knative-sandbox/container-freezer, pull requests merged in 2022-10, with the labels that each got.

#175 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#176 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#177 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#156 Add performance test
  cmd/daemon/main.go
  test/e2e-common.sh
  test/e2e-networking-library.sh
  test/performance/performance-tests.sh
Labels: size/L, lgtm, approved, ok-to-test

#179 drop k8s v1.22 e2e tests
  .github/workflows/kind-e2e-containerd.yaml
  .github/workflows/kubeadm-e2e-crio.yaml
Labels: lgtm, approved, size/XS

#181 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#183 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#182 Add e2e for k8s 1.25
  .github/workflows/kind-e2e-containerd.yaml
  .github/workflows/kubeadm-e2e-crio.yaml
  README.md
Labels: lgtm, size/S, approved

#186 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#185 Fix performance test and integration test
  .github/workflows/kubeadm-e2e-crio.yaml
  test/e2e-common.sh
  test/performance/performance-tests.sh
Labels: lgtm, approved, size/M, kind/bug

#188 Fix default ksvc url
  .github/workflows/kind-e2e-containerd.yaml
  .github/workflows/kubeadm-e2e-crio.yaml
  test/e2e/freeze_test.go
Labels: lgtm, approved, size/XS, kind/cleanup

#187 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#189 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
