Repository knative-sandbox/container-freezer, pull requests merged in 2022-11, with the labels that each got.

#190 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#191 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#192 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#193 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#194 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#195 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#196 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#197 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#198 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#199 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#200 Drop k8s v1.23 from e2e tests
  .github/workflows/kind-e2e-containerd.yaml
  .github/workflows/kubeadm-e2e-crio.yaml
Labels: lgtm, approved, size/XS
