Repository knative-sandbox/container-freezer, pull requests merged in 2022-06, with the labels that each got.

#122 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#123 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#124 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#126 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#127 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: lgtm, size/S, approved

#128 Reduces codecov threshold
  .codecov.yaml
Labels: lgtm, approved, size/XS

#129 Update readme
  README.md
Labels: lgtm, approved, size/XS, needs-ok-to-test, kind/documentation

#131 [main] Upgrade to latest dependencies
  third_party/VENDOR-LICENSE/github.com/bits-and-blooms/bitset/LICENSE
  third_party/VENDOR-LICENSE/github.com/opencontainers/selinux/LICENSE
Labels: lgtm, size/S, approved

#132 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/modules.txt
Labels: size/L, lgtm, approved

#133 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#134 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved
