Repository knative-sandbox/container-freezer, pull requests merged in 2022-07, with the labels that each got.

#136 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#137 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, size/S, approved

#138 Fix to generate yamls for release
  config/common/400-configmap.yaml
  hack/generate-yamls.sh
Labels: lgtm, size/S, approved

#139 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#141 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#142 Updates README to install via latest release
  README.md
Labels: lgtm, size/S, approved

#143 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/opencontainers/selinux/LICENSE
  vendor/knative.dev/networking/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/serving/pkg/networking/constants.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/generate-cert.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#145 Bump go to v1.18
  .github/workflows/kind-e2e-containerd.yaml
  go.mod
  go.sum
Labels: size/L, lgtm, approved

#144 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/changeset/doc.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#146 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/serving/test/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#148 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/modules.txt
Labels: size/L, lgtm, approved

#149 update knative.dev/hack
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/opencontainers/selinux/go-selinux/LICENSE
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/S, approved

#150 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/opencontainers/selinux/LICENSE
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/modules.txt
Labels: lgtm, approved, size/M

#152 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#153 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
